[project]
name = "flow-matching-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "tdqm>=0.0.1",
    "torch>=2.9.1",
]
